<?xml version="1.0" encoding="utf-8"?><Database Name="DW" Class="DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\.;Initial Catalog=DW;Integrated Security=True" SettingsObjectName="DentalWhite.AccesoDatos.Properties.Settings" SettingsPropertyName="DWConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Vw_Paciente" Member="Vw_Paciente">
    <Type Name="Vw_Paciente">
      <Column Name="DescDepartamento" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="DescMunicipio" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="IdPaciente" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Identificacion" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PrimerNombre" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="SegundoNombre" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="PrimerApellido" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="SegundoApelldo" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Edad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Celular" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Correo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CodDepartamento" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CodMunicipio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Barrio" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UserReg" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaReg" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserMod" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FechaMod" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CodTipoDoc" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="DescTipo" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TipoDocumento" Member="TipoDocumento">
    <Type Name="TipoDocumento">
      <Column Name="TipoId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CodTipo" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DescTipo" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Departamentos" Member="Departamentos">
    <Type Name="Departamentos">
      <Column Name="IdDepartamento" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CodDepartamento" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DescDepartamento" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Municipios" Member="Municipios">
    <Type Name="Municipios">
      <Column Name="IdMunicipio" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CodMunicipio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DescMunicipio" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CodDepartamento" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Vw_Hora" Member="Vw_Hora">
    <Type Name="Vw_Hora">
      <Column Name="HoraId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CodHora" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Hora" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="CodEstado" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DescEstado" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Vw_Horario" Member="Vw_Horario">
    <Type Name="Vw_Horario">
      <Column Name="HorarioId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Identificacion" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CodHora" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="CodEstado" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="FechaReg" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserReg" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Hora" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="DescEstado" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PrimerNombre" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="PrimerApellido" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Roles">
      <Column Name="RolId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CodRol" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DesRol" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Usuarios" Member="Usuarios">
    <Type Name="Usuarios">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Correo" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="CodRol" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Activo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Identificacion" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="UserReg" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaReg" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserMod" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FechaMod" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Vw_Doctores" Member="Vw_Doctor">
    <Type Name="Vw_Doctor">
      <Column Name="IdDoctor" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Identificacion" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PrimerNombre" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="SegundoNombre" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="PrimerApellido" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="SegundoApelldo" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Edad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Celular" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Correo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CodDepartamento" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CodMunicipio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Barrio" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UserReg" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaReg" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserMod" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FechaMod" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CodTipoDoc" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="DescDepartamento" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="DescMunicipio" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="DescTipo" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Vw_Cita" Member="Vw_Cita">
    <Type Name="Vw_Cita">
      <Column Name="IdentificacionPaciente" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PrimerNombrePaciente" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="SegundoNombrePaciente" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="PrimerApellidoPaciente" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="SegundoApellidoPaciente" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="EdadPaciente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CelularPaciente" Type="System.String" DbType="NChar(12)" CanBeNull="true" />
      <Column Name="Identificacion" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PrimerNombre" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="SegundoNombre" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="PrimerApellido" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="SegundoApelldo" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Edad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Celular" Type="System.String" DbType="NChar(12)" CanBeNull="true" />
      <Column Name="FechaCita" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CodHora" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="CodEstado" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DescEstado" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="UserReg" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserMod" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Hora" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.sp_Add_Doctor" Method="sp_Add_Doctor">
    <Parameter Name="CodTipoDoc" Parameter="codTipoDoc" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="Identificacion" Parameter="identificacion" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="PrimerNombre" Parameter="primerNombre" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="SegundoNombre" Parameter="segundoNombre" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="PrimerApellido" Parameter="primerApellido" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="SegundoApellido" Parameter="segundoApellido" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Edad" Parameter="edad" Type="System.Int32" DbType="Int" />
    <Parameter Name="FechaNacimiento" Parameter="fechaNacimiento" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Celular" Parameter="celular" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="CodDepartamento" Parameter="codDepartamento" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="CodMunicipio" Parameter="codMunicipio" Type="System.Int32" DbType="Int" />
    <Parameter Name="Barrio" Parameter="barrio" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Estado" Parameter="estado" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="UserReg" Parameter="userReg" Type="System.Int32" DbType="Int" />
    <Parameter Name="FechaReg" Parameter="fechaReg" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="sp_Add_DoctorResult">
      <Column Name="Id" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Add_Horario" Method="sp_Add_Horario">
    <Parameter Name="Identificacion" Parameter="identificacion" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="CodHora" Parameter="codHora" Type="System.String" DbType="NChar(30)" />
    <Parameter Name="CodEstado" Parameter="codEstado" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="FechaReg" Parameter="fechaReg" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="UserReg" Parameter="userReg" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Add_HorarioResult">
      <Column Name="Id" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Add_Paciente" Method="sp_Add_Paciente">
    <Parameter Name="CodTipoDoc" Parameter="codTipoDoc" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="Identificacion" Parameter="identificacion" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="PrimerNombre" Parameter="primerNombre" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="SegundoNombre" Parameter="segundoNombre" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="PrimerApellido" Parameter="primerApellido" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="SegundoApellido" Parameter="segundoApellido" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Edad" Parameter="edad" Type="System.Int32" DbType="Int" />
    <Parameter Name="FechaNacimiento" Parameter="fechaNacimiento" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Celular" Parameter="celular" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="CodDepartamento" Parameter="codDepartamento" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="CodMunicipio" Parameter="codMunicipio" Type="System.Int32" DbType="Int" />
    <Parameter Name="Barrio" Parameter="barrio" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Estado" Parameter="estado" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="UserReg" Parameter="userReg" Type="System.Int32" DbType="Int" />
    <Parameter Name="FechaReg" Parameter="fechaReg" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="sp_Add_PacienteResult">
      <Column Name="Id" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Add_Usuario" Method="sp_Add_Usuario">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Apellido" Parameter="apellido" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="CodRol" Parameter="codRol" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="Activo" Parameter="activo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Identificacion" Parameter="identificacion" Type="System.String" DbType="VarChar(11)" />
    <Parameter Name="FechaReg" Parameter="fechaReg" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="UserReg" Parameter="userReg" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Add_UsuarioResult">
      <Column Name="Id" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Upd_Paciente" Method="sp_Upd_Paciente">
    <Parameter Name="Celular" Parameter="celular" Type="System.String" DbType="NChar(12)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="codDepartamento" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="CodMunicipio" Parameter="codMunicipio" Type="System.Int32" DbType="Int" />
    <Parameter Name="Barrio" Parameter="barrio" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="UserMod" Parameter="userMod" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdPaciente" Parameter="idPaciente" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Upd_Usuario" Method="sp_Upd_Usuario">
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="NChar(15)" />
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="UserMod" Parameter="userMod" Type="System.Int32" DbType="Int" />
    <Parameter Name="Identificacion" Parameter="identificacion" Type="System.String" DbType="VarChar(11)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Upd_Doctor" Method="sp_Upd_Doctor">
    <Parameter Name="Celular" Parameter="celular" Type="System.String" DbType="NChar(12)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="codDepartamento" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="CodMunicipio" Parameter="codMunicipio" Type="System.Int32" DbType="Int" />
    <Parameter Name="Barrio" Parameter="barrio" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="UserMod" Parameter="userMod" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdDoctor" Parameter="idDoctor" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Add_Cita" Method="sp_Add_Cita">
    <Parameter Name="IdentificacionD" Parameter="identificacionD" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="IdentificacionP" Parameter="identificacionP" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="FechaCita" Parameter="fechaCita" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="HorarioId" Parameter="horarioId" Type="System.String" DbType="NChar(30)" />
    <Parameter Name="CodEstado" Parameter="codEstado" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="FechaReg" Parameter="fechaReg" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="UserReg" Parameter="userReg" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Add_CitaResult">
      <Column Name="Id" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Upd_Horario" Method="sp_Upd_Horario">
    <Parameter Name="Identificacion" Parameter="identificacion" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="CodHora" Parameter="codHora" Type="System.String" DbType="NChar(30)" />
    <Parameter Name="CodEstado" Parameter="codEstado" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="UserMod" Parameter="userMod" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Edades" Method="Edades">
    <ElementType Name="EdadesResult">
      <Column Name="Edad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>