#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalWhite.AccesoDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DW")]
	public partial class DBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public DBDataContext() : 
				base(global::DentalWhite.AccesoDatos.Properties.Settings.Default.DWConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Vw_Usuarios> Vw_Usuarios
		{
			get
			{
				return this.GetTable<Vw_Usuarios>();
			}
		}
		
		public System.Data.Linq.Table<Vw_TipoDocumento> Vw_TipoDocumento
		{
			get
			{
				return this.GetTable<Vw_TipoDocumento>();
			}
		}
		
		public System.Data.Linq.Table<Vw_Departamentos> Vw_Departamentos
		{
			get
			{
				return this.GetTable<Vw_Departamentos>();
			}
		}
		
		public System.Data.Linq.Table<Vw_Municipios> Vw_Municipios
		{
			get
			{
				return this.GetTable<Vw_Municipios>();
			}
		}
		
		public System.Data.Linq.Table<Vw_Paciente> Vw_Paciente
		{
			get
			{
				return this.GetTable<Vw_Paciente>();
			}
		}
		
		public System.Data.Linq.Table<Vw_Doctor> Vw_Doctor
		{
			get
			{
				return this.GetTable<Vw_Doctor>();
			}
		}
		
		public System.Data.Linq.Table<Vw_Hora> Vw_Hora
		{
			get
			{
				return this.GetTable<Vw_Hora>();
			}
		}
		
		public System.Data.Linq.Table<Vw_Horarios> Vw_Horarios
		{
			get
			{
				return this.GetTable<Vw_Horarios>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Add_Paciente")]
		public ISingleResult<sp_Add_PacienteResult> sp_Add_Paciente(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodTipoDoc", DbType="NChar(10)")] string codTipoDoc, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Identificacion", DbType="NVarChar(20)")] string identificacion, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrimerNombre", DbType="NVarChar(30)")] string primerNombre, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SegundoNombre", DbType="NVarChar(30)")] string segundoNombre, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrimerApellido", DbType="NVarChar(30)")] string primerApellido, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SegundoApellido", DbType="NVarChar(30)")] string segundoApellido, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Edad", DbType="Int")] System.Nullable<int> edad, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaNacimiento", DbType="DateTime")] System.Nullable<System.DateTime> fechaNacimiento, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Celular", DbType="NChar(10)")] string celular, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="NChar(10)")] string telefono, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="NVarChar(30)")] string correo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodDepartamento", DbType="NVarChar(10)")] string codDepartamento, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodMunicipio", DbType="Int")] System.Nullable<int> codMunicipio, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Barrio", DbType="NVarChar(30)")] string barrio, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="NVarChar(30)")] string direccion, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="Bit")] System.Nullable<bool> estado, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserReg", DbType="Int")] System.Nullable<int> userReg, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaReg", DbType="DateTime")] System.Nullable<System.DateTime> fechaReg)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codTipoDoc, identificacion, primerNombre, segundoNombre, primerApellido, segundoApellido, edad, fechaNacimiento, celular, telefono, correo, codDepartamento, codMunicipio, barrio, direccion, estado, userReg, fechaReg);
			return ((ISingleResult<sp_Add_PacienteResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Add_Usuario")]
		public ISingleResult<sp_Add_UsuarioResult> sp_Add_Usuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="NVarChar(30)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(30)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="NVarChar(30)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellido", DbType="NVarChar(30)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="NVarChar(30)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="NVarChar(15)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodRol", DbType="NChar(10)")] string codRol, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Activo", DbType="Bit")] System.Nullable<bool> activo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Identificacion", DbType="VarChar(11)")] string identificacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaReg", DbType="DateTime")] System.Nullable<System.DateTime> fechaReg, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserReg", DbType="Int")] System.Nullable<int> userReg)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName, password, nombre, apellido, correo, telefono, codRol, activo, identificacion, fechaReg, userReg);
			return ((ISingleResult<sp_Add_UsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Upd_Paciente")]
		public int sp_Upd_Paciente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Celular", DbType="NChar(12)")] string celular, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="NChar(14)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="NVarChar(30)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodDepartamento", DbType="NVarChar(10)")] string codDepartamento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodMunicipio", DbType="Int")] System.Nullable<int> codMunicipio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Barrio", DbType="NVarChar(30)")] string barrio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="NVarChar(30)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserMod", DbType="Int")] System.Nullable<int> userMod, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaMod", DbType="DateTime")] System.Nullable<System.DateTime> fechaMod, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPaciente", DbType="Int")] System.Nullable<int> idPaciente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), celular, telefono, correo, codDepartamento, codMunicipio, barrio, direccion, userMod, fechaMod, idPaciente);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Upd_Usuario")]
		public int sp_Upd_Usuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Celular", DbType="NVarChar(15)")] string celular, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="NVarChar(30)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserMod", DbType="Int")] System.Nullable<int> userMod, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaMod", DbType="DateTime")] System.Nullable<System.DateTime> fechaMod, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Identificacion", DbType="VarChar(11)")] string identificacion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), celular, correo, userMod, fechaMod, identificacion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Add_Doctor")]
		public ISingleResult<sp_Add_DoctorResult> sp_Add_Doctor(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodTipoDoc", DbType="NChar(10)")] string codTipoDoc, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Identificacion", DbType="NVarChar(20)")] string identificacion, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrimerNombre", DbType="NVarChar(30)")] string primerNombre, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SegundoNombre", DbType="NVarChar(30)")] string segundoNombre, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrimerApellido", DbType="NVarChar(30)")] string primerApellido, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SegundoApellido", DbType="NVarChar(30)")] string segundoApellido, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Edad", DbType="Int")] System.Nullable<int> edad, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaNacimiento", DbType="DateTime")] System.Nullable<System.DateTime> fechaNacimiento, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Celular", DbType="NChar(10)")] string celular, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="NChar(10)")] string telefono, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="NVarChar(30)")] string correo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodDepartamento", DbType="NVarChar(10)")] string codDepartamento, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodMunicipio", DbType="Int")] System.Nullable<int> codMunicipio, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Barrio", DbType="NVarChar(30)")] string barrio, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="NVarChar(30)")] string direccion, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="Bit")] System.Nullable<bool> estado, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserReg", DbType="Int")] System.Nullable<int> userReg, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaReg", DbType="DateTime")] System.Nullable<System.DateTime> fechaReg)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codTipoDoc, identificacion, primerNombre, segundoNombre, primerApellido, segundoApellido, edad, fechaNacimiento, celular, telefono, correo, codDepartamento, codMunicipio, barrio, direccion, estado, userReg, fechaReg);
			return ((ISingleResult<sp_Add_DoctorResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Upd_Doctor")]
		public int sp_Upd_Doctor([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Celular", DbType="NChar(12)")] string celular, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="NChar(14)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="NVarChar(30)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodDepartamento", DbType="NVarChar(10)")] string codDepartamento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodMunicipio", DbType="Int")] System.Nullable<int> codMunicipio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Barrio", DbType="NVarChar(30)")] string barrio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="NVarChar(30)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserMod", DbType="Int")] System.Nullable<int> userMod, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaMod", DbType="DateTime")] System.Nullable<System.DateTime> fechaMod, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdDoctor", DbType="Int")] System.Nullable<int> idDoctor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), celular, telefono, correo, codDepartamento, codMunicipio, barrio, direccion, userMod, fechaMod, idDoctor);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Add_Horario")]
		public ISingleResult<sp_Add_HorarioResult> sp_Add_Horario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Identificacion", DbType="NVarChar(20)")] string identificacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodHora", DbType="NChar(30)")] string codHora, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodEstado", DbType="NChar(10)")] string codEstado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaReg", DbType="DateTime")] System.Nullable<System.DateTime> fechaReg, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserReg", DbType="Int")] System.Nullable<int> userReg)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), identificacion, codHora, codEstado, fechaReg, userReg);
			return ((ISingleResult<sp_Add_HorarioResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vw_Usuarios")]
	public partial class Vw_Usuarios
	{
		
		private int _UserId;
		
		private string _UserName;
		
		private string _Password;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Correo;
		
		private string _Telefono;
		
		private string _CodRol;
		
		private System.Nullable<bool> _Activo;
		
		private string _Identificacion;
		
		private int _UserReg;
		
		private System.DateTime _FechaReg;
		
		private System.Nullable<int> _UserMod;
		
		private System.Nullable<System.DateTime> _FechaMod;
		
		private string _DesRol;
		
		public Vw_Usuarios()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int NOT NULL")]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this._Correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodRol", DbType="NChar(10)")]
		public string CodRol
		{
			get
			{
				return this._CodRol;
			}
			set
			{
				if ((this._CodRol != value))
				{
					this._CodRol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activo", DbType="Bit")]
		public System.Nullable<bool> Activo
		{
			get
			{
				return this._Activo;
			}
			set
			{
				if ((this._Activo != value))
				{
					this._Activo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identificacion", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string Identificacion
		{
			get
			{
				return this._Identificacion;
			}
			set
			{
				if ((this._Identificacion != value))
				{
					this._Identificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserReg", DbType="Int NOT NULL")]
		public int UserReg
		{
			get
			{
				return this._UserReg;
			}
			set
			{
				if ((this._UserReg != value))
				{
					this._UserReg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaReg", DbType="DateTime NOT NULL")]
		public System.DateTime FechaReg
		{
			get
			{
				return this._FechaReg;
			}
			set
			{
				if ((this._FechaReg != value))
				{
					this._FechaReg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserMod", DbType="Int")]
		public System.Nullable<int> UserMod
		{
			get
			{
				return this._UserMod;
			}
			set
			{
				if ((this._UserMod != value))
				{
					this._UserMod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaMod", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaMod
		{
			get
			{
				return this._FechaMod;
			}
			set
			{
				if ((this._FechaMod != value))
				{
					this._FechaMod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DesRol", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string DesRol
		{
			get
			{
				return this._DesRol;
			}
			set
			{
				if ((this._DesRol != value))
				{
					this._DesRol = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vw_TipoDocumento")]
	public partial class Vw_TipoDocumento
	{
		
		private int _TipoId;
		
		private string _CodTipo;
		
		private string _DescTipo;
		
		public Vw_TipoDocumento()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoId", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int TipoId
		{
			get
			{
				return this._TipoId;
			}
			set
			{
				if ((this._TipoId != value))
				{
					this._TipoId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodTipo", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string CodTipo
		{
			get
			{
				return this._CodTipo;
			}
			set
			{
				if ((this._CodTipo != value))
				{
					this._CodTipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescTipo", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string DescTipo
		{
			get
			{
				return this._DescTipo;
			}
			set
			{
				if ((this._DescTipo != value))
				{
					this._DescTipo = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vw_Departamentos")]
	public partial class Vw_Departamentos
	{
		
		private int _IdDepartamento;
		
		private string _CodDepartamento;
		
		private string _DescDepartamento;
		
		public Vw_Departamentos()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDepartamento", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int IdDepartamento
		{
			get
			{
				return this._IdDepartamento;
			}
			set
			{
				if ((this._IdDepartamento != value))
				{
					this._IdDepartamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodDepartamento", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string CodDepartamento
		{
			get
			{
				return this._CodDepartamento;
			}
			set
			{
				if ((this._CodDepartamento != value))
				{
					this._CodDepartamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescDepartamento", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string DescDepartamento
		{
			get
			{
				return this._DescDepartamento;
			}
			set
			{
				if ((this._DescDepartamento != value))
				{
					this._DescDepartamento = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vw_Municipios")]
	public partial class Vw_Municipios
	{
		
		private int _IdMunicipio;
		
		private int _CodMunicipio;
		
		private string _DescMunicipio;
		
		private bool _Estado;
		
		private string _CodDepartamento;
		
		public Vw_Municipios()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMunicipio", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int IdMunicipio
		{
			get
			{
				return this._IdMunicipio;
			}
			set
			{
				if ((this._IdMunicipio != value))
				{
					this._IdMunicipio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodMunicipio", DbType="Int NOT NULL")]
		public int CodMunicipio
		{
			get
			{
				return this._CodMunicipio;
			}
			set
			{
				if ((this._CodMunicipio != value))
				{
					this._CodMunicipio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescMunicipio", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string DescMunicipio
		{
			get
			{
				return this._DescMunicipio;
			}
			set
			{
				if ((this._DescMunicipio != value))
				{
					this._DescMunicipio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Bit NOT NULL")]
		public bool Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodDepartamento", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string CodDepartamento
		{
			get
			{
				return this._CodDepartamento;
			}
			set
			{
				if ((this._CodDepartamento != value))
				{
					this._CodDepartamento = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vw_Paciente")]
	public partial class Vw_Paciente
	{
		
		private int _IdPaciente;
		
		private string _Identificacion;
		
		private string _PrimerNombe;
		
		private string _SegundoNombre;
		
		private string _PrimerApellido;
		
		private string _SegundoApellido;
		
		private int _Edad;
		
		private System.DateTime _FechaNacimiento;
		
		private string _Celular;
		
		private string _Telefono;
		
		private string _Correo;
		
		private string _CodDepartamento;
		
		private System.Nullable<int> _CodMunicipio;
		
		private string _Barrio;
		
		private string _Direccion;
		
		private bool _Estado;
		
		private int _UserReg;
		
		private System.DateTime _FechaReg;
		
		private System.Nullable<int> _UserMod;
		
		private System.Nullable<System.DateTime> _FechaMod;
		
		private string _CodTipoDoc;
		
		private string _DescTipo;
		
		private string _DescDepartamento;
		
		private string _DescMunicipio;
		
		private string _UserName;
		
		private string _Password;
		
		public Vw_Paciente()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPaciente", DbType="Int NOT NULL")]
		public int IdPaciente
		{
			get
			{
				return this._IdPaciente;
			}
			set
			{
				if ((this._IdPaciente != value))
				{
					this._IdPaciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identificacion", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Identificacion
		{
			get
			{
				return this._Identificacion;
			}
			set
			{
				if ((this._Identificacion != value))
				{
					this._Identificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimerNombe", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string PrimerNombe
		{
			get
			{
				return this._PrimerNombe;
			}
			set
			{
				if ((this._PrimerNombe != value))
				{
					this._PrimerNombe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegundoNombre", DbType="NVarChar(30)")]
		public string SegundoNombre
		{
			get
			{
				return this._SegundoNombre;
			}
			set
			{
				if ((this._SegundoNombre != value))
				{
					this._SegundoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimerApellido", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string PrimerApellido
		{
			get
			{
				return this._PrimerApellido;
			}
			set
			{
				if ((this._PrimerApellido != value))
				{
					this._PrimerApellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegundoApellido", DbType="NVarChar(30)")]
		public string SegundoApellido
		{
			get
			{
				return this._SegundoApellido;
			}
			set
			{
				if ((this._SegundoApellido != value))
				{
					this._SegundoApellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Edad", DbType="Int NOT NULL")]
		public int Edad
		{
			get
			{
				return this._Edad;
			}
			set
			{
				if ((this._Edad != value))
				{
					this._Edad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacimiento", DbType="DateTime NOT NULL")]
		public System.DateTime FechaNacimiento
		{
			get
			{
				return this._FechaNacimiento;
			}
			set
			{
				if ((this._FechaNacimiento != value))
				{
					this._FechaNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Celular", DbType="NChar(10)")]
		public string Celular
		{
			get
			{
				return this._Celular;
			}
			set
			{
				if ((this._Celular != value))
				{
					this._Celular = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="NChar(10)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="NVarChar(30)")]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this._Correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodDepartamento", DbType="NVarChar(10)")]
		public string CodDepartamento
		{
			get
			{
				return this._CodDepartamento;
			}
			set
			{
				if ((this._CodDepartamento != value))
				{
					this._CodDepartamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodMunicipio", DbType="Int")]
		public System.Nullable<int> CodMunicipio
		{
			get
			{
				return this._CodMunicipio;
			}
			set
			{
				if ((this._CodMunicipio != value))
				{
					this._CodMunicipio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Barrio", DbType="NVarChar(30)")]
		public string Barrio
		{
			get
			{
				return this._Barrio;
			}
			set
			{
				if ((this._Barrio != value))
				{
					this._Barrio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="NVarChar(30)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Bit NOT NULL")]
		public bool Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserReg", DbType="Int NOT NULL")]
		public int UserReg
		{
			get
			{
				return this._UserReg;
			}
			set
			{
				if ((this._UserReg != value))
				{
					this._UserReg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaReg", DbType="DateTime NOT NULL")]
		public System.DateTime FechaReg
		{
			get
			{
				return this._FechaReg;
			}
			set
			{
				if ((this._FechaReg != value))
				{
					this._FechaReg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserMod", DbType="Int")]
		public System.Nullable<int> UserMod
		{
			get
			{
				return this._UserMod;
			}
			set
			{
				if ((this._UserMod != value))
				{
					this._UserMod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaMod", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaMod
		{
			get
			{
				return this._FechaMod;
			}
			set
			{
				if ((this._FechaMod != value))
				{
					this._FechaMod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodTipoDoc", DbType="NChar(10)")]
		public string CodTipoDoc
		{
			get
			{
				return this._CodTipoDoc;
			}
			set
			{
				if ((this._CodTipoDoc != value))
				{
					this._CodTipoDoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescTipo", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string DescTipo
		{
			get
			{
				return this._DescTipo;
			}
			set
			{
				if ((this._DescTipo != value))
				{
					this._DescTipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescDepartamento", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string DescDepartamento
		{
			get
			{
				return this._DescDepartamento;
			}
			set
			{
				if ((this._DescDepartamento != value))
				{
					this._DescDepartamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescMunicipio", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string DescMunicipio
		{
			get
			{
				return this._DescMunicipio;
			}
			set
			{
				if ((this._DescMunicipio != value))
				{
					this._DescMunicipio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vw_Doctor")]
	public partial class Vw_Doctor
	{
		
		private string _Identificacion;
		
		private string _PrimerNombe;
		
		private string _SegundoNombre;
		
		private string _PrimerApellido;
		
		private string _SegundoApellido;
		
		private int _Edad;
		
		private System.DateTime _FechaNacimiento;
		
		private string _Celular;
		
		private string _Telefono;
		
		private string _Correo;
		
		private string _CodDepartamento;
		
		private System.Nullable<int> _CodMunicipio;
		
		private string _Barrio;
		
		private string _Direccion;
		
		private bool _Estado;
		
		private int _UserReg;
		
		private System.DateTime _FechaReg;
		
		private System.Nullable<int> _UserMod;
		
		private System.Nullable<System.DateTime> _FechaMod;
		
		private string _Password;
		
		private string _Nombre;
		
		private string _DescDepartamento;
		
		private string _DescMunicipio;
		
		private string _CodTipoDoc;
		
		private string _DescTipo;
		
		private int _IdDoctor;
		
		public Vw_Doctor()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identificacion", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Identificacion
		{
			get
			{
				return this._Identificacion;
			}
			set
			{
				if ((this._Identificacion != value))
				{
					this._Identificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimerNombe", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string PrimerNombe
		{
			get
			{
				return this._PrimerNombe;
			}
			set
			{
				if ((this._PrimerNombe != value))
				{
					this._PrimerNombe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegundoNombre", DbType="NVarChar(30)")]
		public string SegundoNombre
		{
			get
			{
				return this._SegundoNombre;
			}
			set
			{
				if ((this._SegundoNombre != value))
				{
					this._SegundoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimerApellido", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string PrimerApellido
		{
			get
			{
				return this._PrimerApellido;
			}
			set
			{
				if ((this._PrimerApellido != value))
				{
					this._PrimerApellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegundoApellido", DbType="NVarChar(30)")]
		public string SegundoApellido
		{
			get
			{
				return this._SegundoApellido;
			}
			set
			{
				if ((this._SegundoApellido != value))
				{
					this._SegundoApellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Edad", DbType="Int NOT NULL")]
		public int Edad
		{
			get
			{
				return this._Edad;
			}
			set
			{
				if ((this._Edad != value))
				{
					this._Edad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacimiento", DbType="DateTime NOT NULL")]
		public System.DateTime FechaNacimiento
		{
			get
			{
				return this._FechaNacimiento;
			}
			set
			{
				if ((this._FechaNacimiento != value))
				{
					this._FechaNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Celular", DbType="NChar(10)")]
		public string Celular
		{
			get
			{
				return this._Celular;
			}
			set
			{
				if ((this._Celular != value))
				{
					this._Celular = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="NChar(10)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="NVarChar(30)")]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this._Correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodDepartamento", DbType="NVarChar(10)")]
		public string CodDepartamento
		{
			get
			{
				return this._CodDepartamento;
			}
			set
			{
				if ((this._CodDepartamento != value))
				{
					this._CodDepartamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodMunicipio", DbType="Int")]
		public System.Nullable<int> CodMunicipio
		{
			get
			{
				return this._CodMunicipio;
			}
			set
			{
				if ((this._CodMunicipio != value))
				{
					this._CodMunicipio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Barrio", DbType="NVarChar(30)")]
		public string Barrio
		{
			get
			{
				return this._Barrio;
			}
			set
			{
				if ((this._Barrio != value))
				{
					this._Barrio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="NVarChar(30)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Bit NOT NULL")]
		public bool Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserReg", DbType="Int NOT NULL")]
		public int UserReg
		{
			get
			{
				return this._UserReg;
			}
			set
			{
				if ((this._UserReg != value))
				{
					this._UserReg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaReg", DbType="DateTime NOT NULL")]
		public System.DateTime FechaReg
		{
			get
			{
				return this._FechaReg;
			}
			set
			{
				if ((this._FechaReg != value))
				{
					this._FechaReg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserMod", DbType="Int")]
		public System.Nullable<int> UserMod
		{
			get
			{
				return this._UserMod;
			}
			set
			{
				if ((this._UserMod != value))
				{
					this._UserMod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaMod", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaMod
		{
			get
			{
				return this._FechaMod;
			}
			set
			{
				if ((this._FechaMod != value))
				{
					this._FechaMod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescDepartamento", DbType="VarChar(60)")]
		public string DescDepartamento
		{
			get
			{
				return this._DescDepartamento;
			}
			set
			{
				if ((this._DescDepartamento != value))
				{
					this._DescDepartamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescMunicipio", DbType="VarChar(60)")]
		public string DescMunicipio
		{
			get
			{
				return this._DescMunicipio;
			}
			set
			{
				if ((this._DescMunicipio != value))
				{
					this._DescMunicipio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodTipoDoc", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string CodTipoDoc
		{
			get
			{
				return this._CodTipoDoc;
			}
			set
			{
				if ((this._CodTipoDoc != value))
				{
					this._CodTipoDoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescTipo", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string DescTipo
		{
			get
			{
				return this._DescTipo;
			}
			set
			{
				if ((this._DescTipo != value))
				{
					this._DescTipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDoctor", DbType="Int NOT NULL")]
		public int IdDoctor
		{
			get
			{
				return this._IdDoctor;
			}
			set
			{
				if ((this._IdDoctor != value))
				{
					this._IdDoctor = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vw_Hora")]
	public partial class Vw_Hora
	{
		
		private int _HoraId;
		
		private string _CodHora;
		
		private string _Hora;
		
		private string _CodEstado;
		
		private string _DescEstado;
		
		public Vw_Hora()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoraId", DbType="Int NOT NULL")]
		public int HoraId
		{
			get
			{
				return this._HoraId;
			}
			set
			{
				if ((this._HoraId != value))
				{
					this._HoraId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodHora", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string CodHora
		{
			get
			{
				return this._CodHora;
			}
			set
			{
				if ((this._CodHora != value))
				{
					this._CodHora = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hora", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Hora
		{
			get
			{
				return this._Hora;
			}
			set
			{
				if ((this._Hora != value))
				{
					this._Hora = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodEstado", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string CodEstado
		{
			get
			{
				return this._CodEstado;
			}
			set
			{
				if ((this._CodEstado != value))
				{
					this._CodEstado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescEstado", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string DescEstado
		{
			get
			{
				return this._DescEstado;
			}
			set
			{
				if ((this._DescEstado != value))
				{
					this._DescEstado = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vw_Horarios")]
	public partial class Vw_Horarios
	{
		
		private int _HorarioId;
		
		private string _Identificacion;
		
		private string _CodHora;
		
		private string _CodEstado;
		
		private string _DescEstado;
		
		private string _Hora;
		
		private string _PrimerNombre;
		
		private string _SegundoNombre;
		
		private string _PrimerApellido;
		
		private string _SegundoApellido;
		
		private System.DateTime _FechaReg;
		
		private int _UserReg;
		
		public Vw_Horarios()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HorarioId", DbType="Int NOT NULL")]
		public int HorarioId
		{
			get
			{
				return this._HorarioId;
			}
			set
			{
				if ((this._HorarioId != value))
				{
					this._HorarioId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identificacion", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Identificacion
		{
			get
			{
				return this._Identificacion;
			}
			set
			{
				if ((this._Identificacion != value))
				{
					this._Identificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodHora", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string CodHora
		{
			get
			{
				return this._CodHora;
			}
			set
			{
				if ((this._CodHora != value))
				{
					this._CodHora = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodEstado", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string CodEstado
		{
			get
			{
				return this._CodEstado;
			}
			set
			{
				if ((this._CodEstado != value))
				{
					this._CodEstado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescEstado", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string DescEstado
		{
			get
			{
				return this._DescEstado;
			}
			set
			{
				if ((this._DescEstado != value))
				{
					this._DescEstado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hora", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Hora
		{
			get
			{
				return this._Hora;
			}
			set
			{
				if ((this._Hora != value))
				{
					this._Hora = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimerNombre", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string PrimerNombre
		{
			get
			{
				return this._PrimerNombre;
			}
			set
			{
				if ((this._PrimerNombre != value))
				{
					this._PrimerNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegundoNombre", DbType="NVarChar(30)")]
		public string SegundoNombre
		{
			get
			{
				return this._SegundoNombre;
			}
			set
			{
				if ((this._SegundoNombre != value))
				{
					this._SegundoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimerApellido", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string PrimerApellido
		{
			get
			{
				return this._PrimerApellido;
			}
			set
			{
				if ((this._PrimerApellido != value))
				{
					this._PrimerApellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegundoApellido", DbType="NVarChar(30)")]
		public string SegundoApellido
		{
			get
			{
				return this._SegundoApellido;
			}
			set
			{
				if ((this._SegundoApellido != value))
				{
					this._SegundoApellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaReg", DbType="DateTime NOT NULL")]
		public System.DateTime FechaReg
		{
			get
			{
				return this._FechaReg;
			}
			set
			{
				if ((this._FechaReg != value))
				{
					this._FechaReg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserReg", DbType="Int NOT NULL")]
		public int UserReg
		{
			get
			{
				return this._UserReg;
			}
			set
			{
				if ((this._UserReg != value))
				{
					this._UserReg = value;
				}
			}
		}
	}
	
	public partial class sp_Add_PacienteResult
	{
		
		private System.Nullable<decimal> _Id;
		
		public sp_Add_PacienteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	
	public partial class sp_Add_UsuarioResult
	{
		
		private System.Nullable<decimal> _Id;
		
		public sp_Add_UsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	
	public partial class sp_Add_DoctorResult
	{
		
		private System.Nullable<decimal> _Id;
		
		public sp_Add_DoctorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	
	public partial class sp_Add_HorarioResult
	{
		
		private System.Nullable<decimal> _Id;
		
		public sp_Add_HorarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
